package common

import (
	"github.com/sanda-bunescu/ExploRO/models"
	"gorm.io/gorm"
	"log"
)

func DataSeeder(db *gorm.DB) {
	seedCities(db)
	seedTouristicAttractions(db)
}

func SeedUserCities(db *gorm.DB) ([]models.City, error) {
	var userCities []models.City
	err := db.Where("is_default = ?", true).Find(&userCities).Error
	if err != nil {
		return nil, err
	}
	return userCities, nil
}

func seedCities(db *gorm.DB) {
	var count int64
	db.Model(&models.City{}).Count(&count)

	if count > 0 {
		log.Println("City table already seeded. Skipping seed.")
		return
	}

	baseURL := "/static/images/"

	cities := []models.City{
		{
			Name:        "București",
			Description: "Bucharest, Romania's bustling capital, is a dynamic city that beautifully blends historical charm with modern energy. Known as 'Little Paris' in the early 20th century for its elegant architecture and vibrant cultural scene, the city offers visitors a rich tapestry of experiences—from the colossal Palace of the Parliament to charming Old Town streets filled with cafes, art galleries, and nightlife. It's a hub of art, music, and gastronomy, where past and present coexist in fascinating contrast.",
			ImageURL:    baseURL + "Bucuresti.jpg", IsDefault: true,
		},
		{
			Name:        "Cluj-Napoca",
			Description: "Cluj-Napoca is the unofficial capital of Transylvania and a vibrant academic, cultural, and tech hub. Home to one of Romania’s largest universities, the city pulses with youthful energy and creativity. Visitors are enchanted by its lively squares, bohemian cafes, and a rich cultural calendar full of film festivals, concerts, and art exhibitions. Nestled among rolling hills, Cluj is also a gateway to the stunning Apuseni Mountains.",
			ImageURL:    baseURL + "Cluj-Napoca.jpg", IsDefault: true,
		},
		{
			Name:        "Timișoara",
			Description: "Timișoara, often called the 'City of Freedom,' is renowned for its historical significance as the first city to rise against communism in 1989. With a multicultural identity and stunning architecture influenced by Austrian and Hungarian styles, Timișoara offers visitors a cosmopolitan experience. It’s a city of parks, open-air cafes, and elegant public squares, soon to be celebrated further as a European Capital of Culture.",
			ImageURL:    baseURL + "Timisoara.jpg", IsDefault: true,
		},
		{
			Name:        "Iași",
			Description: "Iași is one of Romania’s most prestigious cultural and academic centers. As the former capital of Moldavia, the city is steeped in history and tradition. It boasts a wealth of historical churches, majestic buildings such as the Palace of Culture, and the oldest university in Romania. Known for its literary heritage and romantic atmosphere, Iași is a place where history whispers from every corner.",
			ImageURL:    baseURL + "Iasi.jpg", IsDefault: true,
		},
		{
			Name:        "Constanța",
			Description: "Constanța is Romania’s main port city on the Black Sea, blending ancient history with beachside relaxation. Founded over 2,500 years ago, it’s one of the oldest continuously inhabited cities in Europe. Visitors can explore Roman mosaics, the iconic Casino building, and vibrant seafront promenades. In summer, Constanța becomes a gateway to Romania’s popular seaside resorts like Mamaia.",
			ImageURL:    baseURL + "Constanta.jpg", IsDefault: true,
		},
		{
			Name:        "Brașov",
			Description: "Set in the heart of the Carpathians, Brașov is one of Romania’s most visited cities, famed for its medieval charm and dramatic mountain backdrop. With cobblestone streets, Gothic-style architecture, and the imposing Black Church, Brașov is a fairytale destination. It’s also a perfect base for visiting the nearby Bran Castle, often associated with the Dracula legend, and the ski resort of Poiana Brașov.",
			ImageURL:    baseURL + "Brasov.jpg", IsDefault: true,
		},
		{
			Name:        "Sibiu",
			Description: "Sibiu is a jewel of Transylvania, known for its well-preserved medieval architecture and Saxon heritage. The city’s historic center is a maze of colorful buildings, cobbled streets, and picturesque squares. A former European Capital of Culture, Sibiu is famous for its ‘houses with eyes,’ vibrant art scene, and proximity to the scenic Făgăraș Mountains. It offers an immersive step back in time with a modern twist.",
			ImageURL:    baseURL + "Sibiu.jpg",
		},
		{
			Name:        "Sinaia",
			Description: "Sinaia, nestled in the Bucegi Mountains, is a popular mountain resort famed for its fairytale-like Peleș Castle—one of the most beautiful in Europe. The town is also a top destination for winter sports and hiking, offering stunning alpine views year-round. Whether you’re exploring royal history or skiing down pristine slopes, Sinaia is a magical escape into Romania’s natural beauty.",
			ImageURL:    baseURL + "Sinaia.jpg",
		},
		{
			Name:        "Sighișoara",
			Description: "Sighișoara is one of the best-preserved medieval towns in Europe and a UNESCO World Heritage Site. Birthplace of Vlad the Impaler, the inspiration behind Dracula, the town enchants visitors with its colorful houses, cobbled streets, and centuries-old clock tower. Walking through Sighișoara feels like stepping into a storybook filled with legends and history.",
			ImageURL:    baseURL + "Sighisoara.jpg",
		},
		{
			Name:        "Maramureș",
			Description: "Maramureș is a region where time seems to stand still. Known for its wooden churches (many UNESCO-listed), traditional villages, and strong cultural identity, it offers a glimpse into Romania’s rural soul. Visitors are welcomed with warm hospitality and age-old traditions, including distinctive wooden gates and lively folk festivals. It’s a haven for those seeking authenticity and tranquility.",
			ImageURL:    baseURL + "Maramures.jpg",
		},
		{
			Name:        "Oradea",
			Description: "Oradea is an architectural gem located near the Hungarian border, known for its exquisite Art Nouveau buildings and vibrant cultural life. The recently restored city center features elegant cafes, colorful facades, and thermal spas. Oradea is quickly becoming one of Romania’s rising stars in tourism, combining beauty, relaxation, and modern urban charm.",
			ImageURL:    baseURL + "Oradea.jpg",
		},
		{
			Name:        "Suceava",
			Description: "Suceava was once the capital of the medieval Principality of Moldavia and remains a spiritual and historical landmark. The city is surrounded by stunning painted monasteries—UNESCO World Heritage Sites—famous for their vivid exterior frescoes. Suceava is a gateway to exploring Northern Romania’s rich Orthodox heritage and natural beauty.",
			ImageURL:    baseURL + "Suceava.jpg",
		},
		{
			Name:        "Târgu Mureș",
			Description: "Târgu Mureș is a culturally diverse city in the heart of Romania, known for its vibrant Hungarian and Romanian communities. It offers a unique architectural blend, exemplified by the Secession-style Palace of Culture. With theaters, botanical gardens, and a laid-back charm, Târgu Mureș is a lesser-known but rewarding destination.",
			ImageURL:    baseURL + "Targu Mures.jpg",
		},
		{
			Name:        "Alba Iulia",
			Description: "Alba Iulia is a symbol of Romanian unity and history, celebrated as the site of the Great Union in 1918. The star-shaped Alba Carolina Fortress is one of the most impressive fortifications in Europe. Visitors can experience ceremonial reenactments, stroll through restored bastions, and explore the city’s deep historical layers.",
			ImageURL:    baseURL + "Alba Iulia.jpg",
		},
		{
			Name:        "Hunedoara",
			Description: "Hunedoara is best known for the spectacular Corvin Castle, a Gothic-Renaissance fortress straight out of a fantasy novel. The castle is one of the largest in Europe and a top tourist attraction. Beyond the fortress, the region is rich in mining history and surrounded by rugged landscapes ideal for outdoor adventures.",
			ImageURL:    baseURL + "Hunedoara.jpg",
		},
		{
			Name:        "Baia Mare",
			Description: "Baia Mare, nestled in the northwestern part of Romania, is known for its mining heritage and breathtaking landscapes. It features a charming old town, open-air museums, and easy access to the scenic Maramureș region. A center of creativity and renewal, Baia Mare is reinventing itself as a cultural and natural getaway.",
			ImageURL:    baseURL + "Baia Mare.jpg",
		},
	}
	db.Create(&cities)
}

func seedTouristicAttractions(db *gorm.DB) {
	var count int64
	db.Model(&models.TouristicAttraction{}).Count(&count)

	if count > 0 {
		log.Println("TouristicAttraction table already seeded. Skipping seed.")
		return
	}

	// Fetch all cities
	var cities []models.City
	db.Find(&cities)

	baseURL := "/static/attractionImages/"

	var attractions []models.TouristicAttraction

	for _, city := range cities {
		switch city.Name {
		case "București":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Palace of the Parliament",
					Description: "One of the largest administrative buildings in the world.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Bucuresti/palace_parliament.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         50.0,
					Link:        "https://parlament.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Herastrau Park",
					Description: "A beautiful park surrounding a lake, perfect for relaxation.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Bucuresti/herastrau.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://parcuri.ro/herastrau",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Romanian Athenaeum",
					Description: "An iconic concert hall and symbol of Romanian culture.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Bucuresti/athenaeum.jpg",
					OpenHours:   "10:00 - 16:00",
					Fee:         20.0,
					Link:        "https://fge.org.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Village Museum",
					Description: "An open-air museum showcasing traditional Romanian village life.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Bucuresti/village_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         25.0,
					Link:        "https://muzeul-satului.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Old Town (Centrul Vechi)",
					Description: "The historic heart of Bucharest filled with cafes, bars, and history.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Bucuresti/old_town.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://bucuresti.travel",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "National Museum of Art of Romania",
					Description: "Houses Romanian and European masterpieces in a former royal palace.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Bucuresti/art_museum.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         30.0,
					Link:        "https://mnar.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Grigore Antipa National Museum of Natural History",
					Description: "A fascinating museum with interactive exhibits and dinosaur skeletons.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Bucuresti/antipa.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         20.0,
					Link:        "https://antipa.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Carturesti Carusel",
					Description: "A stunning bookshop in a historical building, a must-visit for book lovers.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Bucuresti/carturesti.jpg",
					OpenHours:   "10:00 - 22:00",
					Fee:         0.0,
					Link:        "https://carturesti.ro",
					CityId:      city.Id,
				},
			)

		case "Cluj-Napoca":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Botanical Garden",
					Description: "A vast botanical garden with thousands of plant species.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Cluj-Napoca/cluj_botanical.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         20.0,
					Link:        "https://ubbcluj.ro/botanica",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "St. Michael's Church",
					Description: "A Gothic-style church in the main square of Cluj-Napoca.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Cluj-Napoca/st_michael.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         10.0,
					Link:        "https://turismcluj.ro/stmichael",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Central Park (Parcul Central)",
					Description: "A relaxing urban park with paths, a lake, and plenty of greenery.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Cluj-Napoca/central_park.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://clujlife.com/loc/parcul-central/",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Cluj-Napoca Art Museum",
					Description: "Located in the Banffy Palace, it features Romanian and European artworks.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Cluj-Napoca/art_museum_cluj.jpg",
					OpenHours:   "10:00 - 17:00",
					Fee:         15.0,
					Link:        "https://muzeuldearta.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Cetățuia Hill",
					Description: "Offers panoramic views of the city from a historic fortress site.",
					Category:    "Viewpoint",
					ImageUrl:    baseURL + "Cluj-Napoca/cetatuia.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://turismcluj.ro/cetatuia",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Ethnographic Museum of Transylvania",
					Description: "Exhibits Romanian traditional culture and artifacts.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Cluj-Napoca/ethnographic.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         12.0,
					Link:        "https://muzeul-etnografic.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Cluj Arena",
					Description: "Modern stadium hosting sports events and concerts.",
					Category:    "Recreation",
					ImageUrl:    baseURL + "Cluj-Napoca/cluj_arena.jpg",
					OpenHours:   "Varies by event",
					Fee:         0.0,
					Link:        "https://clujarena.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Unirii Square (Piața Unirii)",
					Description: "The central square of Cluj-Napoca surrounded by historical landmarks and lively cafes.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Cluj-Napoca/piata_unirii.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://turismcluj.ro/piata-unirii",
					CityId:      city.Id,
				},
			)

		case "Timișoara":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Victory Square",
					Description: "A historic square surrounded by beautiful architecture.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Timisoara/victory_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://timisoara.ro/victorysquare",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Banat Village Museum",
					Description: "An open-air museum showcasing traditional Romanian houses.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Timisoara/banat_museum.jpg",
					OpenHours:   "10:00 - 16:00",
					Fee:         15.0,
					Link:        "https://muzeulbanatului.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Union Square (Piața Unirii)",
					Description: "One of the most beautiful squares in Romania, with colorful Baroque buildings.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Timisoara/unirii_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://timisoara-info.ro/piata-unirii",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Timișoara Orthodox Cathedral",
					Description: "A massive and iconic cathedral with beautiful mosaics and architecture.",
					Category:    "Religious",
					ImageUrl:    baseURL + "Timisoara/orthodox_cathedral.jpg",
					OpenHours:   "08:00 - 20:00",
					Fee:         0.0,
					Link:        "https://mitropolia-banatului.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Roses Park (Parcul Rozelor)",
					Description: "A lovely park with thousands of roses, often hosting concerts and events.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Timisoara/roses_park.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://primariatm.ro/parcul-rozelor",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Bega River Promenade",
					Description: "Scenic walking paths, cafes, and bike routes along the river.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Timisoara/bega_promenade.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://timisoara-info.ro/bega",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Theresia Bastion",
					Description: "A remnant of Timișoara's old fortress, now home to cafes and exhibitions.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Timisoara/theresia_bastion.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         5.0,
					Link:        "https://muzeulbanatului.ro/theresia",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Liberty Square (Piața Libertății)",
					Description: "A charming central square with vibrant colors and rich history.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Timisoara/liberty_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://timisoara-info.ro/piata-libertatii",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Iulius Town",
					Description: "Modern shopping and entertainment complex with green spaces and a lake.",
					Category:    "Shopping",
					ImageUrl:    baseURL + "Timisoara/iulius_town.jpg",
					OpenHours:   "10:00 - 22:00",
					Fee:         0.0,
					Link:        "https://iuliustown.ro",
					CityId:      city.Id,
				},
			)

		case "Iași":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Palace of Culture",
					Description: "A neo-Gothic masterpiece housing several museums.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Iasi/palace_culture.jpg",
					OpenHours:   "10:00 - 17:00",
					Fee:         30.0,
					Link:        "https://palatulculturii.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Copou Park",
					Description: "A historic park with Romania’s oldest public monument.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Iasi/copou.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://iasi.ro/copou",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Botanical Garden",
					Description: "The oldest and largest botanical garden in Romania.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Iasi/iasi_botanical.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         10.0,
					Link:        "https://botanica.uaic.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Vasile Alecsandri National Theater",
					Description: "A stunning historical building hosting opera and drama shows.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Iasi/iasi_theatre.jpg",
					OpenHours:   "10:00 - 21:00",
					Fee:         20.0,
					Link:        "https://teatrulnationaliasi.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Roznovanu Palace",
					Description: "The current City Hall, a beautiful 19th-century palace.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Iasi/roznovanu.jpg",
					OpenHours:   "08:00 - 16:00",
					Fee:         0.0,
					Link:        "https://primaria-iasi.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Union Square (Piața Unirii)",
					Description: "A historic square commemorating the 1859 Union of the Romanian Principalities.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Iasi/iasi_union_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://iasi.travel/piata-unirii",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Mihai Eminescu Museum",
					Description: "Dedicated to Romania’s national poet.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Iasi/eminescu_museum.jpg",
					OpenHours:   "10:00 - 17:00",
					Fee:         8.0,
					Link:        "https://muzeulliteraturiiiasi.ro",
					CityId:      city.Id,
				},
			)

		case "Constanța":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Constanța Casino",
					Description: "A stunning Art Nouveau building overlooking the Black Sea.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Constanta/constanta_casino.jpg",
					OpenHours:   "09:00 - 19:00",
					Fee:         0.0,
					Link:        "https://constanta.ro/casino",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Dolphinarium (Delfinariul)",
					Description: "Fun for all ages with dolphin and sea lion shows.",
					Category:    "Family",
					ImageUrl:    baseURL + "Constanta/dolphinarium.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         30.0,
					Link:        "https://delfinariu.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Microreservation Constanța",
					Description: "A small nature reserve and zoo that showcases native Romanian wildlife, including deer, peacocks, and various birds. Located next to the Dolphinarium.",
					Category:    "Family",
					ImageUrl:    baseURL + "Constanta/microreservation.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         15.0,
					Link:        "https://delfinariu.ro/microrezervatia",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Folk Art Museum",
					Description: "Displays traditional Romanian crafts and costumes.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Constanta/folk_art.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeeconstanta.ro/arta-populara",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Ovidiu Square",
					Description: "A central square with a statue of Roman poet Ovid and historic buildings.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Constanta/ovidiu_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://constanta.ro/ovidiu",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Museum of National History and Archeology",
					Description: "Rich in artifacts from Greek, Roman, and early Romanian eras.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Constanta/constanta_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         20.0,
					Link:        "https://minac.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Carol I Mosque",
					Description: "An important religious and architectural site offering panoramic views from its minaret.",
					Category:    "Religious",
					ImageUrl:    baseURL + "Constanta/carol_mosque.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         5.0,
					Link:        "https://moscheia-carol.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Tomis Port",
					Description: "Lively area filled with seafood restaurants, bars, and music for a great evening by the sea.",
					Category:    "Entertainment",
					ImageUrl:    baseURL + "Constanta/tomis_port.jpg",
					OpenHours:   "10:00 - 02:00",
					Fee:         0.0,
					Link:        "https://tomisport.ro",
					CityId:      city.Id,
				},
			)
		case "Brașov":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Black Church",
					Description: "Iconic Gothic cathedral dominating Brașov's skyline.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Brasov/black_church.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         15.0,
					Link:        "https://brasovtravelguide.com/blackchurch",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Council Square (Piața Sfatului)",
					Description: "Historic central square surrounded by colorful buildings.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Brasov/council_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://brasovtourism.com/square",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Tampa Mountain",
					Description: "Hike or take the cable car for panoramic city views.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Brasov/tampa_mountain.jpg",
					OpenHours:   "08:00 - 20:00",
					Fee:         20.0,
					Link:        "https://brasovnature.ro/tampa",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Catherine’s Gate",
					Description: "A beautifully preserved medieval gate from 1559.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Brasov/catherines_gate.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         5.0,
					Link:        "https://brasovhistory.ro/catherine",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Liberty Bear Sanctuary",
					Description: "A safe haven for rescued brown bears, located near Zărnești. Visitors can learn about bear conservation and see the animals in a natural forest habitat.",
					Category:    "Wildlife",
					ImageUrl:    baseURL + "Brasov/bear_sanctuary.jpg",
					OpenHours:   "09:00 - 16:00",
					Fee:         40.0,
					Link:        "https://millionsoffriends.org/en/liberty-bear-sanctuary",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Rope Street (Strada Sforii)",
					Description: "One of the narrowest streets in Europe.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Brasov/rope_street.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://brasovguide.ro/ropestreet",
					CityId:      city.Id,
				},
			)
		case "Sibiu":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Brukenthal Palace",
					Description: "One of Romania’s top art museums, housing impressive European art collections.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Sibiu/brukenthal.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         20.0,
					Link:        "https://brukenthalmuseum.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Council Tower",
					Description: "An iconic tower offering panoramic views of Sibiu's old town.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sibiu/council_tower.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://sibiu.ro/counciltower",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Large Square (Piața Mare)",
					Description: "The historic heart of Sibiu surrounded by stunning baroque architecture.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Sibiu/piata_mare.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sibiu.ro/piatamare",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Small Square (Piața Mică)",
					Description: "A charming square known for its picturesque buildings and intimate vibe.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Sibiu/piata_mica.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sibiu.ro/piatamica",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Bridge of Lies",
					Description: "A legendary iron bridge with local myths and romantic stories.",
					Category:    "Landmark",
					ImageUrl:    baseURL + "Sibiu/bridge_lies.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sibiu.ro/bridgeoflies",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Evangelical Cathedral",
					Description: "Gothic cathedral with an impressive spire and fascinating crypts.",
					Category:    "Religious",
					ImageUrl:    baseURL + "Sibiu/evangelical_cathedral.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         15.0,
					Link:        "https://sibiu.ro/evangelical",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "ASTRA Museum of Traditional Folk Civilization",
					Description: "One of Europe’s largest open-air museums dedicated to folk traditions.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Sibiu/astra.jpg",
					OpenHours:   "09:00 - 19:00",
					Fee:         25.0,
					Link:        "https://muzeulastra.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Stairs Passage",
					Description: "A photogenic medieval passageway connecting Sibiu’s upper and lower town.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sibiu/stairs_passage.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sibiu.ro/stairspassage",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Steam Locomotive Museum",
					Description: "A museum for train enthusiasts featuring restored steam locomotives.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Sibiu/steam_locomotive.jpg",
					OpenHours:   "10:00 - 16:00",
					Fee:         10.0,
					Link:        "https://sibiu.ro/steamlocomotive",
					CityId:      city.Id,
				},
			)
		case "Sinaia":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Peleș Castle",
					Description: "A Neo-Renaissance masterpiece, former royal residence, and one of Europe's most stunning castles.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sinaia/peles_castle.jpg",
					OpenHours:   "09:15 - 17:00",
					Fee:         50.0,
					Link:        "https://peles.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Pelisor Castle",
					Description: "A smaller Art Nouveau palace near Peleș Castle with rich interiors and royal history.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sinaia/pelisor.jpg",
					OpenHours:   "09:15 - 17:00",
					Fee:         30.0,
					Link:        "https://peles.ro/pelisor",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sinaia Monastery",
					Description: "A historic monastery founded in the 17th century, blending Byzantine and Brâncovenesc styles.",
					Category:    "Religious",
					ImageUrl:    baseURL + "Sinaia/sinaia_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         0.0,
					Link:        "https://sinaia-monastery.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Bușteni Cable Car & Bucegi Mountains",
					Description: "Take the cable car to spectacular mountain views and hiking trails in the Bucegi range.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Sinaia/busteni_cablecar.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         35.0,
					Link:        "https://telecabina.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Dimitrie Ghica Park",
					Description: "A scenic, landscaped park perfect for a relaxing stroll and family outings.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Sinaia/ghica_park.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sinaia.ro/ghicapark",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sinaia Casino",
					Description: "An elegant early 20th-century building now used for exhibitions and events.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Sinaia/sinaia_casino.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         20.0,
					Link:        "https://casinosinaia.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "George Enescu Memorial House",
					Description: "Museum dedicated to Romania’s greatest composer, located in his summer home.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Sinaia/enescu_house.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeul-enescu.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Prahova Valley Ski Slopes",
					Description: "Popular skiing and snowboarding destination during winter with various difficulty slopes.",
					Category:    "Sport",
					ImageUrl:    baseURL + "Sinaia/prahova_ski.jpg",
					OpenHours:   "09:00 - 16:00 (seasonal)",
					Fee:         80.0,
					Link:        "https://ski-romania.ro/prahova",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sinaia Railway Station",
					Description: "One of Romania’s most beautiful railway stations with royal waiting rooms and vintage decor.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sinaia/sinaia_station.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://cfrcalatori.ro",
					CityId:      city.Id,
				},
			)
		case "Sighișoara":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Clock Tower",
					Description: "A 64-meter-high medieval tower offering panoramic views and housing a history museum.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sighisoara/sighisoara_clocktower.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         15.0,
					Link:        "https://muzeusighisoara.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Birthplace of Vlad the Impaler",
					Description: "The house where Vlad Dracula (Vlad the Impaler) was born in 1431, now a restaurant and museum.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sighisoara/vlad_house.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         10.0,
					Link:        "https://draculasighisoara.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Covered Staircase (Scholar’s Stairs)",
					Description: "A 17th-century covered wooden staircase built for students climbing the hill to school.",
					Category:    "Landmark",
					ImageUrl:    baseURL + "Sighisoara/covered_stairs.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sighisoara.ro/scholarstairs",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sighișoara Citadel",
					Description: "A UNESCO World Heritage Site, this fortified old town is among the best-preserved in Europe.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sighisoara/sighisoara_citadel.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://unesco.org/sighisoara",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Tailors’ Tower",
					Description: "A defensive tower once guarding the main gate, now an entry to the citadel.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sighisoara/tailors_tower.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sighisoara.ro/tailors",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Tinsmiths’ Tower",
					Description: "Another well-preserved tower forming part of the city's medieval defenses.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sighisoara/tinsmiths_tower.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sighisoara.ro/tinsmiths",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sighișoara Weapon Museum",
					Description: "Small museum displaying medieval weapons and armor, located near the Clock Tower.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Sighisoara/weapon_museum.jpg",
					OpenHours:   "10:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeusighisoara.ro/weapon",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Blacksmiths’ Tower",
					Description: "One of the few original defensive towers that remains largely intact.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Sighisoara/blacksmiths_tower.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sighisoara.ro/blacksmiths",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Festival Medieval Sighișoara",
					Description: "Annual medieval festival with costumes, music, theater, and crafts inside the citadel.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Sighisoara/medieval_festival.jpg",
					OpenHours:   "Last weekend of July",
					Fee:         0.0,
					Link:        "https://festivalmedieval.ro",
					CityId:      city.Id,
				},
			)
		case "Maramureș":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Merry Cemetery",
					Description: "A unique cemetery with colorful, hand-painted wooden crosses, located in Săpânța.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "Maramures/merry_cemetery.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://sapanta.ro/merry-cemetery",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Wooden Churches of Maramureș",
					Description: "A UNESCO World Heritage site featuring unique wooden churches spread across the region.",
					Category:    "Religious",
					ImageUrl:    baseURL + "Maramures/wooden_churches.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://maramures.ro/wooden-churches",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Bârsana Monastery",
					Description: "A beautiful wooden monastery with tall spires, one of Maramureș's most iconic landmarks.",
					Category:    "Religious",
					ImageUrl:    baseURL + "Maramures/barsana_monastery_spires.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         5.0,
					Link:        "https://barsana.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Village Museum of Maramureș",
					Description: "An open-air museum showcasing traditional wooden houses, artifacts, and tools from the region.",
					Category:    "Museum",
					ImageUrl:    baseURL + "Maramures/village_museum_maramures.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         10.0,
					Link:        "https://muzeulmaramures.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sighet Memorial Museum",
					Description: "A museum dedicated to the victims of communist repression in Romania, housed in a former prison.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Maramures/sighet_memorial.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         15.0,
					Link:        "https://memorialsighet.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Vaser Valley Narrow Gauge Railway",
					Description: "A scenic ride through the forests of Maramureș on a historic narrow-gauge steam train.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Maramures/vaser_valley_train.jpg",
					OpenHours:   "May - October",
					Fee:         30.0,
					Link:        "https://maramures.ro/vaser-valley-train",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Mocănița Train",
					Description: "A historic steam train offering a journey through the picturesque Maramureș mountains.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Maramures/mocanita_train.jpg",
					OpenHours:   "May - October",
					Fee:         30.0,
					Link:        "https://mocanita.com",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Maramureș Mountains Nature Park",
					Description: "A protected natural area offering hiking, wildlife watching, and breathtaking views.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Maramures/maramures_mountains.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://parcnaturalmaramures.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Iza River Valley",
					Description: "A scenic valley in Maramureș known for its picturesque villages and traditional wooden architecture.",
					Category:    "Nature",
					ImageUrl:    baseURL + "Maramures/iza_river_valley.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://maramures.ro/iza-valley",
					CityId:      city.Id,
				},
			)
		case "Oradea":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Oradea Fortress",
					Description: "A historic fortress dating back to the 12th century, offering panoramic views of the city.",
					Category:    "Historical",
					ImageUrl:    baseURL + "Oradea/oradea_fortress.jpg",
					OpenHours:   "09:00 - 19:00",
					Fee:         10.0,
					Link:        "https://oradea.ro/fortress",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Black Hawk Palace",
					Description: "A beautiful Art Nouveau building, now housing a cultural center and art exhibitions.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "black_hawk_palace.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         5.0,
					Link:        "https://oradea.ro/black-hawk-palace",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Moon Church",
					Description: "A unique baroque church, famous for its astronomical clock and moon phase indicator.",
					Category:    "Historical",
					ImageUrl:    baseURL + "moon_church.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         5.0,
					Link:        "https://oradea.ro/moon-church",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Union Square",
					Description: "A historic square surrounded by baroque and Secessionist architecture, and a popular gathering place.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "union_square_oradea.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://oradea.ro/union-square",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Oradea City Hall",
					Description: "A stunning neo-baroque building with impressive architecture and the famous “Golden Roof.”",
					Category:    "Cultural",
					ImageUrl:    baseURL + "oradea_city_hall.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         0.0,
					Link:        "https://oradea.ro/city-hall",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Black Eagle Palace",
					Description: "An Art Nouveau-style building with a famous glass-covered arcade, a symbol of Oradea’s grandeur.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "black_eagle_palace.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         5.0,
					Link:        "https://oradea.ro/black-eagle-palace",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Ady Endre Museum",
					Description: "A museum dedicated to the Hungarian poet Ady Endre, located in his childhood home.",
					Category:    "Museum",
					ImageUrl:    baseURL + "ady_endre_museum.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         8.0,
					Link:        "https://oradea.ro/ady-endre-museum",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Oradea Zoo",
					Description: "A family-friendly zoo located in a lush green park with a variety of animals and birds.",
					Category:    "Nature",
					ImageUrl:    baseURL + "oradea_zoo.jpg",
					OpenHours:   "10:00 - 19:00",
					Fee:         15.0,
					Link:        "https://oradea.ro/zoo",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Rimanoczy Palace",
					Description: "A magnificent Art Nouveau building with beautiful facades and architectural details.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "rimanoczy_palace.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         5.0,
					Link:        "https://oradea.ro/rimanoczy-palace",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Nymphaea Aquapark",
					Description: "A large water park offering slides, pools, and relaxation areas for families and tourists.",
					Category:    "Leisure",
					ImageUrl:    baseURL + "nymphaea_aquapark.jpg",
					OpenHours:   "10:00 - 20:00",
					Fee:         40.0,
					Link:        "https://oradea.ro/nymphaea-aquapark",
					CityId:      city.Id,
				},
			)
		case "Suceava":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Suceava Fortress",
					Description: "A historical fortress built in the 14th century, once the capital of the Principality of Moldavia.",
					Category:    "Historical",
					ImageUrl:    baseURL + "suceava_fortress.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         10.0,
					Link:        "https://suceava.ro/fortress",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Voroneț Monastery",
					Description: "A UNESCO World Heritage Site, famous for its vibrant blue frescoes and peaceful surroundings.",
					Category:    "Religious",
					ImageUrl:    baseURL + "voronet_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         5.0,
					Link:        "https://voronet.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Moldovița Monastery",
					Description: "A UNESCO-listed monastery known for its well-preserved frescoes and beautiful surroundings.",
					Category:    "Religious",
					ImageUrl:    baseURL + "moldovita_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         5.0,
					Link:        "https://moldovita.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Humor Monastery",
					Description: "A stunning painted monastery with vivid frescoes, part of the UNESCO-listed Painted Churches of Northern Moldova.",
					Category:    "Religious",
					ImageUrl:    baseURL + "humor_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         5.0,
					Link:        "https://humor.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Suceava History Museum",
					Description: "The museum showcases the region’s rich history, including the medieval period and the time of the Moldavian Principality.",
					Category:    "Museum",
					ImageUrl:    baseURL + "suceava_history_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         15.0,
					Link:        "https://suceava.ro/history-museum",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Painted Churches of Northern Moldova",
					Description: "A UNESCO World Heritage Site known for its famous painted churches, including Voroneț, Moldovița, and Sucevița.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "painted_churches.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://paintedchurches.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sucevița Monastery",
					Description: "A stunning UNESCO World Heritage Site, known for its intricate exterior frescoes depicting biblical scenes.",
					Category:    "Religious",
					ImageUrl:    baseURL + "sucevita_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         5.0,
					Link:        "https://sucevita.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Căpriana Monastery",
					Description: "One of the oldest and most important monasteries in Moldova, known for its picturesque location and historical significance.",
					Category:    "Religious",
					ImageUrl:    baseURL + "capriana_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         5.0,
					Link:        "https://capriana.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Bucovina Village Museum",
					Description: "An open-air museum showcasing traditional rural life in Bucovina, featuring historical buildings and artifacts.",
					Category:    "Museum",
					ImageUrl:    baseURL + "bucovina_village_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://bucovina.ro/village-museum",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Rarău Mountain",
					Description: "A picturesque mountain offering hiking opportunities and breathtaking views of the surrounding landscapes.",
					Category:    "Nature",
					ImageUrl:    baseURL + "rarau_mountain.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://rarau.ro",
					CityId:      city.Id,
				},
			)
		case "Târgu Mureș":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Palace of Culture",
					Description: "An architectural gem in Târgu Mureș, home to several museums, including an art gallery and a library.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "palace_of_culture.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://palatulculturii.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Târgu Mureș Zoo",
					Description: "A well-maintained zoo featuring a variety of animal species, perfect for family visits.",
					Category:    "Nature",
					ImageUrl:    baseURL + "targu_mures_zoo.jpg",
					OpenHours:   "09:00 - 19:00",
					Fee:         15.0,
					Link:        "https://targumures.ro/zoo",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Catedrala Ortodoxă",
					Description: "A beautiful Orthodox cathedral known for its impressive architecture and religious significance.",
					Category:    "Religious",
					ImageUrl:    baseURL + "catedrala_ortodoxa.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         0.0,
					Link:        "https://targumures.ro/catedrala-ortodoxa",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Mureș River Promenade",
					Description: "A relaxing riverside walk offering great views of the city and a chance to enjoy the local flora and fauna.",
					Category:    "Nature",
					ImageUrl:    baseURL + "mures_river_promenade.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://targumures.ro/mures-river",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Mureș County Museum",
					Description: "This museum showcases the history, art, and culture of the region, with a variety of exhibits on display.",
					Category:    "Museum",
					ImageUrl:    baseURL + "mures_county_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeulmures.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Ethnographic Park",
					Description: "An open-air museum showcasing traditional rural architecture and craftsmanship from the Mureș region.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "ethnographic_park.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         5.0,
					Link:        "https://targumures.ro/ethnographic-park",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Unirii Square",
					Description: "A historic square in the center of Târgu Mureș, surrounded by impressive architecture and cafes.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "unirii_square.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://targumures.ro/unirii-square",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Târgu Mureș Fortress",
					Description: "A historic fortification offering panoramic views of the city, great for history enthusiasts.",
					Category:    "Historical",
					ImageUrl:    baseURL + "targu_mures_fortress.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         10.0,
					Link:        "https://targumures.ro/fortress",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Teleki-Bolyai Library",
					Description: "A historic library with a vast collection of books, especially on Romanian culture and history.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "teleki_bolyai_library.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         0.0,
					Link:        "https://targumures.ro/library",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Târgu Mureș Citadel",
					Description: "A well-preserved medieval citadel offering historical insights into the city’s development over centuries.",
					Category:    "Historical",
					ImageUrl:    baseURL + "targu_mures_citadel.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         10.0,
					Link:        "https://targumures.ro/citadel",
					CityId:      city.Id,
				},
			)
		case "Alba Iulia":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Alba Carolina Fortress",
					Description: "A star-shaped fortress with impressive fortifications, offering panoramic views and historical reenactments.",
					Category:    "Historical",
					ImageUrl:    baseURL + "alba_carolina_fortress.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         20.0,
					Link:        "https://alba.ro/alba-carolina-fortress",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Union Hall (Sala Unirii)",
					Description: "The historic hall where the Great Union of 1918 was signed, a key moment in Romania’s history.",
					Category:    "Historical",
					ImageUrl:    baseURL + "union_hall.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://alba.ro/union-hall",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Roman Catholic Cathedral",
					Description: "A beautiful gothic-style cathedral located in the heart of Alba Iulia, part of the historic religious heritage.",
					Category:    "Religious",
					ImageUrl:    baseURL + "roman_catholic_cathedral.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         0.0,
					Link:        "https://alba.ro/roman-catholic-cathedral",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The National Museum of the Union",
					Description: "A museum dedicated to the history of the Great Union of 1918 and the formation of modern Romania.",
					Category:    "Museum",
					ImageUrl:    baseURL + "national_museum_of_the_union.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeulunirii.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Bastionul Săracilor",
					Description: "The Poor's Bastion, one of the fortification bastions in the Alba Carolina Fortress, with interactive exhibits.",
					Category:    "Historical",
					ImageUrl:    baseURL + "bastionul_saracilor.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         5.0,
					Link:        "https://alba.ro/bastionul-saracilor",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Albota Monastery",
					Description: "A peaceful Orthodox monastery located near the city, offering beautiful architecture and a serene environment.",
					Category:    "Religious",
					ImageUrl:    baseURL + "albota_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         0.0,
					Link:        "https://alba.ro/albota-monastery",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Vasile Goldiș Park",
					Description: "A spacious park near the city center, perfect for relaxation and enjoying nature, with monuments and sculptures.",
					Category:    "Nature",
					ImageUrl:    baseURL + "vasile_goldis_park.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://alba.ro/vasile-goldis-park",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Catherine’s Gate",
					Description: "A historic gateway to the Alba Iulia Fortress, with a rich history dating back to the 18th century.",
					Category:    "Historical",
					ImageUrl:    baseURL + "catherines_gate.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://alba.ro/catherines-gate",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The City Hall and the Historic Center",
					Description: "The city hall and the surrounding historic center offer a glimpse into the architecture and culture of Alba Iulia.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "city_hall_center.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         0.0,
					Link:        "https://alba.ro/city-hall-center",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Marble Lake",
					Description: "A natural lake in the city, ideal for a relaxing walk, boating, or enjoying the surrounding park.",
					Category:    "Nature",
					ImageUrl:    baseURL + "marble_lake.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://alba.ro/marble-lake",
					CityId:      city.Id,
				},
			)
		case "Hunedoara":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Corvin Castle",
					Description: "One of the largest and most impressive castles in Europe, showcasing Gothic and Renaissance architecture.",
					Category:    "Historical",
					ImageUrl:    baseURL + "corvin_castle.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         40.0,
					Link:        "https://castelulcorvinilor.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Hunedoara Mining Museum",
					Description: "A museum showcasing the rich mining history of the region, with interactive exhibits and historic mining equipment.",
					Category:    "Museum",
					ImageUrl:    baseURL + "hunedoara_mining_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeulminelui.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Dacian Fortresses of the Orăștie Mountains",
					Description: "A UNESCO World Heritage site featuring ancient Dacian fortresses offering stunning views and historical significance.",
					Category:    "Historical",
					ImageUrl:    baseURL + "dacian_fortresses.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://unescosites.org/dacian-fortresses",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Prislop Monastery",
					Description: "A peaceful Orthodox monastery surrounded by nature, known for its spiritual significance and scenic location.",
					Category:    "Religious",
					ImageUrl:    baseURL + "prislop_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         0.0,
					Link:        "https://prislopmonastery.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Măgura Uroiului",
					Description: "An archaeological site with the remains of a Dacian settlement, offering historical insights into the ancient culture of the region.",
					Category:    "Historical",
					ImageUrl:    baseURL + "magura_uroiului.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://hunedoara.ro/magura-uroiului",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Sarmizegetusa Regia",
					Description: "The capital of the Dacian Kingdom, known for its impressive archaeological sites and ancient temples.",
					Category:    "Historical",
					ImageUrl:    baseURL + "sarmizegetusa_regia.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         15.0,
					Link:        "https://sarmizegetusa.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Deva Fortress",
					Description: "A historic fortress overlooking the city of Deva, offering panoramic views of the surrounding landscapes.",
					Category:    "Historical",
					ImageUrl:    baseURL + "deva_fortress.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         10.0,
					Link:        "https://deva.ro/deva-fortress",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Lake Cincis",
					Description: "A beautiful lake near Hunedoara, perfect for a relaxing day out, with opportunities for fishing and picnicking.",
					Category:    "Nature",
					ImageUrl:    baseURL + "lake_cincis.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://hunedoara.ro/lake-cincis",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Făget Forest",
					Description: "A forest park near Hunedoara, ideal for hiking, biking, and enjoying the natural beauty of the region.",
					Category:    "Nature",
					ImageUrl:    baseURL + "faget_forest.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://hunedoara.ro/faget-forest",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Băile Tușnad",
					Description: "A historical spa town known for its mineral waters and therapeutic baths, located near Hunedoara.",
					Category:    "Wellness",
					ImageUrl:    baseURL + "baile_tusnad.jpg",
					OpenHours:   "09:00 - 18:00",
					Fee:         20.0,
					Link:        "https://bailetusnad.ro",
					CityId:      city.Id,
				},
			)
		case "Baia Mare":
			attractions = append(attractions,
				models.TouristicAttraction{
					Name:        "Baia Mare Art Museum",
					Description: "One of the most important art museums in Romania, showcasing a vast collection of Romanian and international art.",
					Category:    "Museum",
					ImageUrl:    baseURL + "baia_mare_art_museum.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         15.0,
					Link:        "https://muzeulartelor.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Maramureș Village Museum",
					Description: "An open-air ethnographic museum showcasing the traditional architecture and lifestyle of the Maramureș region.",
					Category:    "Museum",
					ImageUrl:    baseURL + "maramures_village_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         10.0,
					Link:        "https://muzeulmaramuresului.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Călinești Village",
					Description: "A picturesque village near Baia Mare, known for its wooden churches and traditional Maramureș architecture.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "calinesti_village.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://maramures.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Dealul Mare",
					Description: "A hill offering panoramic views of Baia Mare and the surrounding mountains, perfect for a peaceful hike or picnic.",
					Category:    "Nature",
					ImageUrl:    baseURL + "dealul_mare.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://baia-mare.ro/dealul-mare",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Wooden Churches of Maramureș",
					Description: "A collection of UNESCO-listed wooden churches known for their unique architecture and spiritual significance.",
					Category:    "Cultural",
					ImageUrl:    baseURL + "wooden_churches.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://maramures.ro/wooden-churches",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Mina de Aur",
					Description: "A historic gold mine offering tours and an insight into the history of gold mining in the region.",
					Category:    "Historical",
					ImageUrl:    baseURL + "mina_de_aur.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         20.0,
					Link:        "https://baia-mare.ro/mina-de-aur",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Lacul Firiza",
					Description: "A beautiful lake surrounded by mountains, ideal for fishing, boating, or just relaxing by the water.",
					Category:    "Nature",
					ImageUrl:    baseURL + "lacul_firiza.jpg",
					OpenHours:   "Open 24/7",
					Fee:         0.0,
					Link:        "https://baia-mare.ro/lacul-firiza",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "The Văratec Monastery",
					Description: "A historic Orthodox monastery, known for its serene location and beautiful frescoes.",
					Category:    "Religious",
					ImageUrl:    baseURL + "varatec_monastery.jpg",
					OpenHours:   "08:00 - 18:00",
					Fee:         0.0,
					Link:        "https://baia-mare.ro/varatec-monastery",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Baia Mare Ethnographic Museum",
					Description: "The ethnographic museum in Baia Mare exhibits the rich cultural history and traditions of the Maramureș region.",
					Category:    "Museum",
					ImageUrl:    baseURL + "baia_mare_ethnographic_museum.jpg",
					OpenHours:   "09:00 - 17:00",
					Fee:         12.0,
					Link:        "https://muzeul-etnografic.ro",
					CityId:      city.Id,
				},
				models.TouristicAttraction{
					Name:        "Moisei Memorial House",
					Description: "A memorial museum dedicated to the victims of the Moisei massacre during World War II, offering historical insight into the region’s war history.",
					Category:    "Historical",
					ImageUrl:    baseURL + "moisei_memorial.jpg",
					OpenHours:   "10:00 - 18:00",
					Fee:         5.0,
					Link:        "https://maramures.ro/moisei-memorial",
					CityId:      city.Id,
				},
			)

		}

	}

	db.Create(&attractions)
}
